[[mapping-date-format]]
=== `format`

在 JSON 文档中，日期表示为字符串。Elasticsearch 使用一组预配置格式来识别这些字符串并将其解析为一个长值，该值表示 UTC 中的 _milliseconds-the-epoch_ 。

除了<<built-in-date-formats,内置格式>>，还可以使用熟悉的 `yyyy/MM/dd` 语法指定<<custom-date-formats,自定义格式>>：

[source,js]
--------------------------------------------------
PUT my_index
{
  "mappings": {
    "_doc": {
      "properties": {
        "date": {
          "type":   "date",
          "format": "yyyy-MM-dd"
        }
      }
    }
  }
}
--------------------------------------------------
// CONSOLE

支持日期值和<<date-math,日期匹配>>表达式的很多 APIs，例如 `now-1m/d` -- 当前时间减去一个月，会被四舍五入到最近的一天。

[[custom-date-formats]]
==== 自定义日期格式

支持完全可自定义的日期格式。语法在 http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html[Joda 文档]进行了解释。

[[built-in-date-formats]]
==== 内置格式

以下大多数格式都有 `严格` 的伴生格式，这意味着年月日必须分别准确地使用 4，2，2 位数字，可能会补 0。例如，日期 `5/11/1` 会被认为是不合法的，并且需要改写为 `2005/11/01` 才可以被日期解释器接受。

使用严格日期格式需要在日期格式的名称加上 `strict_` 前缀，例如 `strict_date_optional_time` 代替 `date_optional_time`。

严格日期特别有用，当日期字段被动态映射以确保没有意外地将不相关的字符串映射为日期。

下表列出了支持的所有默认 ISO 格式：

`epoch_millis`::

    毫秒级时间戳。注意，它受 Java 的 `Long.MIN_VALUE` 和 `Long.MAX_VALUE` 限制。

`epoch_second`::

    秒级时间戳。注意，它受 Java 的 `Long.MIN_VALUE` /1000 和 `Long.MAX_VALUE` /1000 限制。

[[strict-date-time]]`date_optional_time` 或 `strict_date_optional_time`::

    通用的 ISO 日期时间分析器，其中日期是必需的，时间是可选的。
    http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateOptionalTimeParser--[全部详情].

`basic_date`::

    日期的基本格式：四位数的年，两位数的月和两位数的日。

`basic_date_time`::

    由日期和时间组成的基本格式，以 'T' 分隔：`yyyyMMdd'T'HHmmss.SSSZ` 。

`basic_date_time_no_millis`::

    由日期和时间（没有毫秒）组成的基本格式，以 'T' 分隔：`yyyyMMdd'T'HHmmssZ` 。

`basic_ordinal_date`::

    四位数年份和三位数年份日组成的完整序数日期。

`basic_ordinal_date_time`::

    四位数年份和三位数年份日组成的完整序数日期和时间：`yyyyDDD'T'HHmmss.SSSZ` 。

`basic_ordinal_date_time_no_millis`::

    不带毫秒的完整序数日期和时间的格式化程序，使用四位数字的年份和三位数字的年份日：`YYYYDDD'T'HHMMSSZ` 。

`basic_time`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数、三位数字的毫秒数和时区偏移量组成的格式： `HHmmss.SSSZ` 。

`basic_time_no_millis`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数和时区偏移量组成的格式： `HHmmssZ` 。

`basic_t_time`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数和三位数字的毫秒数和时区偏移量组成，并以 'T' 为前缀的格式： `'T'HHmmss.SSSZ` 。

`basic_t_time_no_millis`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数和时区偏移量组成，并以 'T' 为前缀的格式： `'T'HHmmssZ` 。

`basic_week_date` 或 `strict_basic_week_date`::

    完整日期的基本格式，四位数字的 weekyear、两位数字的周数和一位数字的天数。

`basic_week_date_time` 或 `strict_basic_week_date_time`::

    由基本日期和时间组成的格式，以 'T' 分隔： `xxxx'W'wwe'T'HHmmss.SSSZ` 。

`basic_week_date_time_no_millis` 或 `strict_basic_week_date_time_no_millis`::

    由基本的日期和时间（没有毫秒）组成的格式，以 'T' 分隔： `xxxx'W'wwe'T'HHmmssZ` 。

`date` 或 `strict_date`::

    由四位数字的年份、两位数字的月份和两位数字的天数组成的格式： `yyyy-MM-dd` 。

`date_hour` 或 `strict_date_hour`::

    由完整日期和两位数字的小时数组成的格式： `yyyy-MM-dd'T'HH` 。

`date_hour_minute` 或 `strict_date_hour_minute`::

    由完整日期、两位数字的小时数和两位数字的分钟数组成的格式： `yyyy-MM-dd'T'HH:mm` 。

`date_hour_minute_second` 或 `strict_date_hour_minute_second`::

    由完整日期、两位数字的小时数、两位数字的分钟数和两位数字的秒数组成的格式： `yyyy-MM-dd'T'HH:mm:ss` 。

`date_hour_minute_second_fraction` 或 `strict_date_hour_minute_second_fraction`::

    由完整日期、两位数字的小时数、两位数字的分钟数、两位数字的分钟数和三位数字的秒的分数组成的格式： `yyyy-MM-dd'T'HH:mm:ss.SSS` 。

`date_hour_minute_second_millis` 或 `strict_date_hour_minute_second_millis`::

    由完整日期、两位数字的小时数、两位数字的分钟数、两位数字的分钟数和三位数字的秒的分数组成的格式： `yyyy-MM-dd'T'HH:mm:ss.SSS` 。

`date_time` 或 `strict_date_time`::

    由完整日期和时间组成，并以 'T' 分隔的格式： `yyyy-MM-dd'T'HH:mm:ss.SSSZZ` 。

`date_time_no_millis` 或 `strict_date_time_no_millis`::

    由完整日期和时间（没有毫秒）组成，并以 'T' 分隔的格式： `yyyy-MM-dd'T'HH:mm:ssZZ` 。

`hour` 或 `strict_hour`::

    两位数字的小时数的格式： `HH` 。

`hour_minute` 或 `strict_hour_minute`::

    两位数字的小时数和两位数字的分钟数： `HH:mm` 。

`hour_minute_second` 或 `strict_hour_minute_second`::

    由两位数字的小时数、两位数字的分钟数和两位数字的秒数组成的格式： `HH:mm:ss` 。

`hour_minute_second_fraction` 或 `strict_hour_minute_second_fraction`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数和三位数字的秒数的分数组成的格式： `HH:mm:ss.SSS`。

`hour_minute_second_millis` 或 `strict_hour_minute_second_millis`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数和三位数字的秒数的分数组成的格式： `HH:mm:ss.SSS` 。

`ordinal_date` 或 `strict_ordinal_date`::

    由序数日期中四位数字的年份和三位数字的天数组成的格式： `yyyy-DDD` 。

`ordinal_date_time` 或 `strict_ordinal_date_time`::

    由完整的序数日期和时间（四位数字的年份和三位数字的天数）组成的格式： `yyyy-DDD'T'HH:mm:ss.SSSZZ` 。

`ordinal_date_time_no_millis` 或 `strict_ordinal_date_time_no_millis`::

    由完整的序数日期和没有毫秒数的时间（四位数字的年份和三位数字的天数）组成的格式： `yyyy-DDD'T'HH:mm:ssZZ` 。

`time` 或 `strict_time`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数、三位数字的秒数的分数和时间偏移量组成的格式： `HH:mm:ss.SSSZZ` 。

`time_no_millis` 或 `strict_time_no_millis`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数和时间偏移量组成的格式： `HH:mm:ssZZ` 。

`t_time` 或 `strict_t_time`::

    由两位数字的小时数、两位数字的分钟数、两位数字的秒数、三位数字的秒数的分数和时间偏移量组成，并以 'T' 为前缀的格式： `'T'HH:mm:ss.SSSZZ` 。

`t_time_no_millis` 或 `strict_t_time_no_millis`::

    由两位数字小时数、两位数字的分钟数、两位数字的秒数和时间偏移量组成的格式，并以 'T' 为前缀： `'T'HH:mm:ssZZ` 。

`week_date` 或 `strict_week_date`::

    由四位数字的 weekyear、两位数字的周数和一位数字的天数组成的完整日期的格式： `xxxx-'W'ww-e` 。

`week_date_time` 或 `strict_week_date_time`::

    由完整的 weekyear 日期和时间组成，并以 'T' 分隔的格式： `xxxx-'W'ww-e'T'HH:mm:ss.SSSZZ` 。

`week_date_time_no_millis` 或 `strict_week_date_time_no_millis`::

    由完整的 weekyear 和时间组成，并以 'T' 分隔的格式： `xxxx-'W'ww-e'T'HH:mm:ssZZ` 。

`weekyear` 或 `strict_weekyear`::

    四位数字的 weekyear： `xxxx` 。

`weekyear_week` 或 `strict_weekyear_week`::

    由四位数字的 weekyear 和两位数字的周数组成的格式： `xxxx-'W'ww` 。

`weekyear_week_day` 或 `strict_weekyear_week_day`::

    由四位数字的 weekyear，两位数字的周数和一位数字的天数组成的格式： `xxxx-'W'ww-e` 。

`year` 或 `strict_year`::

    四位数字的年份： `yyyy` 。

`year_month` 或 `strict_year_month`::

    由四位数字的年份和两位数字的月份组成的格式： `yyyy-MM` 。

`year_month_day` 或 `strict_year_month_day`::

    由四位数字的年份、两位数字的月份和两位数字的天数组成的格式： `yyyy-MM-dd` 。

