[[alias]]
=== 别名数据类型

NOTE: 只能在具有单一映射类型的索引上指定字段别名。
要添加字段别名，索引必须已在 6.0 或更高版本中创建，或者是设置了 `index.mapping.single_type：true` 的旧索引。
请参考 <<removal-of-types>> 以查阅更多信息。

`alias` 映射定义了索引中字段的备用名称。别名可用于代替<<search, 搜索>>请求中的目标字段，
以及选择的其他 API，如<<search-field-caps, 字段能力（field capabilities）>>。

[source,js]
--------------------------------
PUT trips
{
  "mappings": {
    "_doc": {
      "properties": {
        "distance": {
          "type": "long"
        },
        "route_length_miles": {
          "type": "alias",
          "path": "distance" // <1>
        },
        "transit_mode": {
          "type": "keyword"
        }
      }
    }
  }
}

GET _search
{
  "query": {
    "range" : {
      "route_length_miles" : {
        "gte" : 39
      }
    }
  }
}
--------------------------------
// CONSOLE

<1> 目标字段的路径。请注意，这必须是完整路径，包括任何父对象，例如 `object1.object2.field` 。

搜索请求的几乎所有组件都接受字段别名。特别地，别名可用于查询、聚合和排序字段，以及请求时的 `docvalue_fields` 、 `stored_fields` 、建议和高亮显示。
在访问字段值时，脚本也支持别名。对于例外的情况，请参考 <<unsupported-apis, 不支持的 API>>。

在搜索请求以及请求字段功能（field capabilities）时的某些部分，可以提供字段通配符模式。在这些情况下，除了具体字段之外，通配符模式还将匹配字段别名：

[source,js]
--------------------------------
GET trips/_field_caps?fields=route_*,transit_mode
--------------------------------
// CONSOLE
// TEST[continued]

[[alias-targets]]
==== 别名目标

别名的目标有一些限制：

  * 目标必须是具体字段，而不是对象或其他字段别名。
  * 目标字段必须在创建别名时存在。
  * 如果定义了嵌套对象，则字段别名必须与其目标具有相同的嵌套范围。

此外，字段别名只能有一个目标。这意味着无法使用字段别名来查询单个子句中的多个目标字段。

[[unsupported-apis]]
==== 不支持的 API

不支持写入字段别名：尝试在索引或更新请求中使用别名将会失败。同样，别名不能用作 `copy_to` 或多字段的目标。

由于文档源中不存在别名，因此在执行源过滤时不能使用别名。例如，以下请求将返回 `_source` 的空结果：

[source,js]
--------------------------------
GET /_search
{
  "query" : {
    "match_all": {}
  },
  "_source": "route_length_miles"
}
--------------------------------
// CONSOLE
// TEST[continued]

目前，只有搜索和字段功能（field capabilities） API 才会接受并解析字段别名。其他接受字段名称的 API 不能与字段别名一起使用，例如<<docs-termvectors, 词向量（term vectors）>>。

最后，某些查询允许从索引文档中获取查询信息，例如 `terms` 、 `geo_shape` 和 `more_like_this` 。
由于在获取文档时不支持字段别名，因此指定查找路径的查询部分不能通过其别名定位到一个字段。